### ISSUE TITLE
Add support for Swedish Holidays

### ISSUE THREAD

**Issue by AnderssonPeter** [ryanss/python-holidays#55]
Doing some googling the following could be used as data source:
http://api.dryg.net/dagar/v2.1/YYYY, http://api.dryg.net/dagar/v2.1/YYYY/MM, http://api.dryg.net/dagar/v2.1/YYYY/MM/DD
Result for 2017
```yaml
{
  "cachetid": "2017-05-10 14:05:17",
  "version": "2.1",
  "uri": "/dagar/v2.1/2017",
  "startdatum": "2017-01-01",
  "slutdatum": "2017-12-31",
  "dagar": [
    {
      "datum": "2017-01-01",
      "veckodag": "Söndag",
      "arbetsfri dag": "Ja",
      "röd dag": "Ja",
      "vecka": "52",
      "dag i vecka": "7",
      "helgdag": "Nyårsdagen",
      "namnsdag": [],
      "flaggdag": "Nyårsdagen"
    },
    {
      "datum": "2017-01-02",
      "veckodag": "Måndag",
      "arbetsfri dag": "Nej",
      "röd dag": "Nej",
      "vecka": "01",
      "dag i vecka": "1",
      "namnsdag": [
        "Svea"
      ],
      "flaggdag": ""
    },
    {
...
```

Documentation can be found at: https://api.dryg.net
